### ISSUE TITLE
Features to support

### ISSUE THREAD

**Issue by daejunpark** [a16z/halmos#15]
Features to support:
- [x] Known external contract calls (#21)
- [x] Known external account interactions
- [x] Pretty-print counterexamples (storage variable names, external calls, etc)
- [x] Immutable storage variables (#21)
- [x] Struct type parameters
- [x] Overwrite bytecode for new accounts created by setup (#75)

Cheatcodes to support:
- [x] prank (#62)
- [ ] expectRevert / testFail
- [ ] expectEmit

**Comment by 0xPhaze** [comment]
+1 for `signextend` otherwise arithmetic for sub 32 bytes types cannot be checked.

**Comment by karmacoma-eth** [comment]
Opcode support moved into its own issue: https://github.com/a16z/halmos/issues/129

**Comment by aviggiano** [comment]
+1 for `expectEmit`

It can be particularly useful in differential testing

**Comment by daejunpark** [comment]
moved remaining items to #409, closing
